version: '3'

services:
    db:
        image: postgres:14.3
        restart: ${DOCKER_RESTART_MODE}
        ports:
            - "${DOCKER_DB_PORT}:5432"
        environment:
            POSTGRES_DB: ${DOCKER_DB_NAME}
            POSTGRES_USER: ${DOCKER_DB_USER}
            POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD} 
        container_name: ${DOCKER_CONTAINER_NAME}
        volumes:
            - ./docker-db/postgres:/var/lib/postgresql/data 

          