## Entorno de .vscode/settings.json, Ej: rest-client-example.json. 
## Seleccionar entorno con CMD+ALT+E
@SOY_VARIABLE=Soy el contenido

### CiudadGeografica listar
curl --location --request POST '{{encomiendassp_api}}/api/gral/ciudadGeografica/listar' \
# curl --location --request POST '{{encomiendassp_api}}/api/gral/ciudadGeografica/listar/c/cuentaCore' \
--header 'Authorization: Bearer {{encomiendassp_token}}' \
--header 'xrn-so: web' --header 'xrn-version: 1.0.0' \
--header 'Content-Type: application/json' \
--data-raw '{
    "all": false,
    "page": 1,
    "limit": 10,
    "orderBy": "nombre asc",
    "filterList":[],
    "atributos":"",
    "detalles":[],
    "extra":""
}'
###"filterList":  [{"data":"idCiudadGeografica", "op":"eq", "value":100, "group":"and"}]



### CiudadGeografica agregar
curl --location --request POST '{{encomiendassp_api}}/api/gral/ciudadGeografica/agregar' \
--header 'Authorization: Bearer {{encomiendassp_token}}' \
--header 'xrn-so: web' --header 'xrn-version: 1.0.0' \
--header 'Content-Type: application/json' \
--data-raw '{
    "departamentoGeografico": {"idDepartamentoGeografico":100},
	"nombre": "Fdo de la Mora",
	"activo": true
    
}'


### CiudadGeografica modificar
curl --location --request POST '{{encomiendassp_api}}/api/gral/ciudadGeografica/modificar' \
--header 'Authorization: Bearer {{encomiendassp_token}}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "idCiudadGeografica": 0,
    "departamentoGeografico": {"idDepartamentoGeografico":0},
	"nombre": "",
	"activo": true
    
}'


### CiudadGeografica eliminar
curl --location --request POST '{{encomiendassp_api}}/api/zk/usuario/eliminar' \
--header 'Authorization: Bearer {{encomiendassp_token}}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "idCiudadGeografica": 0
}'

// KGC-NOREPLACE-OTROS-INI
// KGC-NOREPLACE-OTROS-FIN
