
/* CONSTRAINT DROP GRAL_CIUDAD_GEOGRAFICA */
ALTER TABLE IF EXISTS GRAL_CIUDAD_GEOGRAFICA 
	DROP  CONSTRAINT IF EXISTS "GRAL_CIUDAD_GEOGRAFICA-id_departamento_geografico_fk"; 











DROP TABLE IF EXISTS GRAL_CIUDAD_GEOGRAFICA;
DROP SEQUENCE IF EXISTS GRAL_CIUDAD_GEOGRAFICA_SEQ;


DROP TABLE IF EXISTS GRAL_DEPARTAMENTO_GEOGRAFICO;
DROP SEQUENCE IF EXISTS GRAL_DEPARTAMENTO_GEOGRAFICO_SEQ;


